# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b6a798f1af270c5104964a8736e597552009f67bf9b826e7ea99cffa70a1dc91d05e63c988df74ecf34f302967760c03057794cfa7fd14758577e11ba69b3a9

test:
  secret_key_base: c93892e3fa5dbd398c514e488740111527c5bee6b053a122999cef4c586756d3db0e53ac9aa6cb40a82bd11b812a0857f357c896a32288d95107d0d5a7af9ad7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
